"""Assemble the ``megatron sft`` command line and its environment from UI state."""
from __future__ import annotations

import hashlib
import pathlib
import shlex

from . import param_schema as ps
from .constants import PROJECT_ROOT


def megatron_bin(train_venv: str) -> str:
    return str(pathlib.Path(train_venv) / "bin" / "megatron")


def build_argv(state: dict, model_path: str, dataset: str, output_dir: str, train_venv: str) -> list[str]:
    """Full argv: [megatron, sft, --model ..., ..., --output_dir ...] + fixed flags + advanced args."""
    argv = [megatron_bin(train_venv), "sft", "--model", model_path, "--dataset", dataset]
    for flag, vals in ps.state_flags(state):
        argv += [f"--{flag}", *vals]
    for flag, val in ps.FIXED_FLAGS:
        argv += [f"--{flag}", val]
    argv += ["--output_dir", output_dir]
    extra = ps.parse_extra_args(state.get("extra_args") or "")
    if extra:
        argv = _override(argv, extra)
    return argv


def _override(argv: list[str], extra: list[str]) -> list[str]:
    """Advanced args win: drop any earlier occurrence of a flag that the extra list also sets."""
    extra_flags = {t for t in extra if t.startswith("--")}
    out: list[str] = []
    skip = False
    for tok in argv:
        if tok.startswith("--"):
            skip = tok in extra_flags
            if skip:
                continue
        elif skip:
            continue
        out.append(tok)
    return out + extra


def build_env(state: dict, train_venv: str, master_port: int, modelscope_cache: str = "",
              hf_home: str = "") -> dict[str, str]:
    s = ps.compute_derived(state)
    root = str(PROJECT_ROOT)
    return {
        "CUDA_VISIBLE_DEVICES": ",".join(ps.gpu_list(s)),
        "NPROC_PER_NODE": str(s["nproc"]),
        "MASTER_ADDR": "127.0.0.1",
        "MASTER_PORT": str(master_port),
        "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
        "MODELSCOPE_CACHE": modelscope_cache or f"{root}/.cache/modelscope",
        "HF_HOME": hf_home or f"{root}/.cache/huggingface",
        "PATH": f"{train_venv}/bin:$PATH",
    }


def render_shell(argv: list[str]) -> str:
    """One flag per line, values shell-quoted."""
    lines: list[str] = []
    cur: list[str] = []
    for tok in argv:
        if tok.startswith("--") and cur:
            lines.append(" ".join(cur))
            cur = []
        cur.append(tok if tok.startswith("--") else shlex.quote(tok))
    if cur:
        lines.append(" ".join(cur))
    return " \\\n  ".join(lines)


def render_script(env: dict[str, str], cmd: list[str], run_root: str) -> str:
    """Bash wrapper written to <run_root>/ui/run.sh: exports env, runs the command, records the exit code."""
    lines = ["#!/usr/bin/env bash", "# generated by megatron-swift webui", f"cd {shlex.quote(str(PROJECT_ROOT))}"]
    for k, v in env.items():
        lines.append(f"export {k}={v}" if k == "PATH" else f"export {k}={shlex.quote(v)}")
    lines.append(f"mkdir -p {shlex.quote(run_root)}/ui")
    lines.append(render_shell(cmd))
    lines.append("rc=$?")
    lines.append(f"echo $rc > {shlex.quote(run_root)}/ui/exit_code")
    lines.append("exit $rc")
    return "\n".join(lines) + "\n"


def argv_sha256(argv: list[str]) -> str:
    return hashlib.sha256("\0".join(argv).encode("utf-8")).hexdigest()


def parse_flags(argv: list[str]) -> dict[str, list[str]]:
    """flag (without dashes) -> following value tokens."""
    out: dict[str, list[str]] = {}
    cur = None
    for tok in argv:
        if tok.startswith("--"):
            cur = tok[2:]
            out.setdefault(cur, [])
        elif cur is not None:
            out[cur].append(tok)
    return out
