"""Persisted UI settings: paths.env (shared + per-host override) and ui.json."""
from __future__ import annotations

import json
import os
import pathlib
import shlex
from dataclasses import asdict, dataclass, field

from .constants import (DEFAULT_DATA_ROOT, DEFAULT_MODEL, DEFAULT_OUTPUT_ROOT, DEFAULT_TRAIN_VENV, DEFAULT_UI_PORT,
                        PROJECT_ROOT, SETTINGS_DIR, hostname)


@dataclass
class EnvField:
    name: str
    label: str
    kind: str = "dir"                 # dir | file | str
    default: str = ""
    help: str = ""
    auto_create: bool = False


ENV_FIELDS: list[EnvField] = [
    EnvField("MODEL_ROOT", "默认模型路径", "dir", DEFAULT_MODEL, "HF 格式模型目录（--model）"),
    EnvField("DATA_ROOT", "数据目录", "dir", DEFAULT_DATA_ROOT, "Train 页扫描此目录下的 *.jsonl"),
    EnvField("OUTPUT_ROOT", "输出根目录", "dir", DEFAULT_OUTPUT_ROOT, "每次训练在其下建 <run_id>/（--output_dir）", True),
    EnvField("TRAIN_VENV", "训练环境 (.venv-swift)", "dir", DEFAULT_TRAIN_VENV, "含 bin/megatron 的 Python 环境"),
    EnvField("MODELSCOPE_CACHE", "ModelScope 缓存", "dir", str(PROJECT_ROOT / ".cache" / "modelscope"), "", True),
    EnvField("HF_HOME", "HuggingFace 缓存", "dir", str(PROJECT_ROOT / ".cache" / "huggingface"), "", True),
]
ENV_BY_NAME = {f.name: f for f in ENV_FIELDS}


@dataclass
class UiSettings:
    port: int = DEFAULT_UI_PORT
    auth_user: str = "swift"
    auth_password: str = "swift"
    fake_train: bool = False
    fake_interval: float = 2.0
    model_table: dict = field(default_factory=lambda: {"Qwen3.8-Flash-Next": DEFAULT_MODEL})


UI_JSON = SETTINGS_DIR / "ui.json"


def load_ui_settings() -> UiSettings:
    if UI_JSON.is_file():
        try:
            data = json.loads(UI_JSON.read_text(encoding="utf-8"))
            known = {k: v for k, v in data.items() if k in UiSettings.__dataclass_fields__}
            return UiSettings(**known)
        except (json.JSONDecodeError, TypeError):
            pass
    return UiSettings()


def save_ui_settings(s: UiSettings) -> str:
    SETTINGS_DIR.mkdir(parents=True, exist_ok=True)
    _atomic_write(UI_JSON, json.dumps(asdict(s), indent=2, ensure_ascii=False) + "\n")
    return str(UI_JSON)


def _atomic_write(path: pathlib.Path, text: str) -> None:
    tmp = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


def parse_env_file(path: pathlib.Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        if k.startswith("export "):
            k = k[7:].strip()
        v = v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
            v = v[1:-1]
        out[k] = v
    return out


def render_env_file(values: dict[str, str]) -> str:
    return "".join(f"{k}={shlex.quote(str(v))}\n" for k, v in values.items())


def shared_env_path() -> pathlib.Path:
    return SETTINGS_DIR / "paths.env"


def host_env_path(host: str | None = None) -> pathlib.Path:
    return SETTINGS_DIR / f"paths.{host or hostname()}.env"


def load_paths_env(host: str | None = None) -> dict[str, str]:
    values = {f.name: f.default for f in ENV_FIELDS}
    values.update(parse_env_file(shared_env_path()))
    values.update(parse_env_file(host_env_path(host)))
    return values


def save_paths_env(values: dict[str, str], scope: str = "shared") -> str:
    SETTINGS_DIR.mkdir(parents=True, exist_ok=True)
    path = shared_env_path() if scope == "shared" else host_env_path()
    clean = {k: str(v).strip() for k, v in values.items() if k in ENV_BY_NAME}
    if scope != "shared":   # host override only stores entries that differ from the shared file
        shared = {**{f.name: f.default for f in ENV_FIELDS}, **parse_env_file(shared_env_path())}
        clean = {k: v for k, v in clean.items() if shared.get(k) != v}
    _atomic_write(path, "# generated by megatron-swift webui\n" + render_env_file(clean))
    return str(path)


def validate_paths_env(values: dict[str, str]) -> list[tuple[str, str, str]]:
    """Return rows (name, status, message) where status is ok | warn | error."""
    rows: list[tuple[str, str, str]] = []
    for f in ENV_FIELDS:
        v = (values.get(f.name) or "").strip()
        if not v:
            rows.append((f.name, "error", "未设置"))
            continue
        p = pathlib.Path(v)
        if f.kind == "dir":
            if p.is_dir():
                msg = v
                if f.name == "TRAIN_VENV" and not (p / "bin" / "megatron").is_file():
                    rows.append((f.name, "error", f"缺少 bin/megatron: {v}"))
                    continue
                rows.append((f.name, "ok", msg))
            elif f.auto_create:
                rows.append((f.name, "warn", f"目录不存在，启动时自动创建: {v}"))
            else:
                rows.append((f.name, "error", f"目录不存在: {v}"))
        elif f.kind == "file":
            rows.append((f.name, "ok" if p.is_file() else "error", v if p.is_file() else f"文件不存在: {v}"))
        else:
            rows.append((f.name, "ok", v))
    return rows
